// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package stubs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SayHiClient is the client API for SayHi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SayHiClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type sayHiClient struct {
	cc grpc.ClientConnInterface
}

func NewSayHiClient(cc grpc.ClientConnInterface) SayHiClient {
	return &sayHiClient{cc}
}

func (c *sayHiClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/sample_module.sample_package.SayHi/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SayHiServer is the server API for SayHi service.
// All implementations must embed UnimplementedSayHiServer
// for forward compatibility
type SayHiServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedSayHiServer()
}

// UnimplementedSayHiServer must be embedded to have forward compatible implementations.
type UnimplementedSayHiServer struct {
}

func (UnimplementedSayHiServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedSayHiServer) mustEmbedUnimplementedSayHiServer() {}

// UnsafeSayHiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SayHiServer will
// result in compilation errors.
type UnsafeSayHiServer interface {
	mustEmbedUnimplementedSayHiServer()
}

func RegisterSayHiServer(s grpc.ServiceRegistrar, srv SayHiServer) {
	s.RegisterService(&SayHi_ServiceDesc, srv)
}

func _SayHi_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SayHiServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample_module.sample_package.SayHi/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SayHiServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SayHi_ServiceDesc is the grpc.ServiceDesc for SayHi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SayHi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sample_module.sample_package.SayHi",
	HandlerType: (*SayHiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _SayHi_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "SayHi.proto",
}
